### PR TITLE
Upgrade SadConsole to v10

### PR DESCRIPTION
**Pull request by Thraka**
Very cool project! This PR upgrades SadConsole to v10 and uses the new startup system.

I tried to replicate your code style, using `global::` calls.

### CODE REVIEW

**Comment by highbyte** [comment]
Thanks for the nice comment and PR, much appreciated!

As of late I've mainly focused on Blazor WASM/SkiaSharp and native Slik.NET/OpenGL pixel shader rendering.
Implementing a menu and the machine code monitor in the SadConsole app is still on the todo list :)

**Review by highbyte — APPROVED** [review]
LGTM

**Comment by Thraka** [comment]
@highbyte Blazor is something I REALLY want to get running for SadConsole, but I don't want to roll my own opengl sprite engine!

**Comment by highbyte** [comment]
@Thraka I don't know if it's viable for SadConsole, but if you could target SkiaSharp as rendering backend you'll get the benefit that SkiaSharp has Blazor integration via SkiaSharp.Views.Blazor (drawing on as HTML Canvas). I use that in this emulator, and share Skia rendering code between a Blazor and native host. Performance wise for me it seems to do the trick for a C64 text based screen if I pre-render the character set as images and draw them to the Skia canvas.

Though I had to change gear when I wanted to render a C64 bitmap screen, then I couldn't get the perf I needed from SkiaSharp. That's when I started looking in to using a OpenGL fragment shader to do 2D drawing. That is currently only in the native Silk.NET host. I'm looking forward for Silk.NET 3.0 that hopefully includes Blazor WASM support for the Silk.NET API.

**Pull request merged**
